# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_platform_pb2 as agent__platform__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub(object):
    """============================================================================
    Services
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrganization = channel.unary_unary(
                '/agent_platform.ControlPlane/CreateOrganization',
                request_serializer=agent__platform__pb2.CreateOrgRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.OrganizationProto.FromString,
                _registered_method=True)
        self.GetOrganization = channel.unary_unary(
                '/agent_platform.ControlPlane/GetOrganization',
                request_serializer=agent__platform__pb2.GetOrgRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.OrganizationProto.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/agent_platform.ControlPlane/ListOrganizations',
                request_serializer=agent__platform__pb2.ListOrgsRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ListOrgsResponse.FromString,
                _registered_method=True)
        self.DeleteOrganization = channel.unary_unary(
                '/agent_platform.ControlPlane/DeleteOrganization',
                request_serializer=agent__platform__pb2.DeleteOrgRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.DeleteOrgResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/agent_platform.ControlPlane/RegisterAgent',
                request_serializer=agent__platform__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.AgentIdentityProto.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/agent_platform.ControlPlane/GetAgent',
                request_serializer=agent__platform__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.AgentIdentityProto.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/agent_platform.ControlPlane/ListAgents',
                request_serializer=agent__platform__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.DeactivateAgent = channel.unary_unary(
                '/agent_platform.ControlPlane/DeactivateAgent',
                request_serializer=agent__platform__pb2.DeactivateAgentRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.DeactivateAgentResponse.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/agent_platform.ControlPlane/SetPolicy',
                request_serializer=agent__platform__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.PolicyProto.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/agent_platform.ControlPlane/GetPolicy',
                request_serializer=agent__platform__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.PolicyProto.FromString,
                _registered_method=True)
        self.EvaluatePolicy = channel.unary_unary(
                '/agent_platform.ControlPlane/EvaluatePolicy',
                request_serializer=agent__platform__pb2.EvaluatePolicyRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.PolicyDecisionProto.FromString,
                _registered_method=True)
        self.SetBudget = channel.unary_unary(
                '/agent_platform.ControlPlane/SetBudget',
                request_serializer=agent__platform__pb2.SetBudgetRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.BudgetProto.FromString,
                _registered_method=True)
        self.GetBudget = channel.unary_unary(
                '/agent_platform.ControlPlane/GetBudget',
                request_serializer=agent__platform__pb2.GetBudgetRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.BudgetProto.FromString,
                _registered_method=True)
        self.CheckBudget = channel.unary_unary(
                '/agent_platform.ControlPlane/CheckBudget',
                request_serializer=agent__platform__pb2.CheckBudgetRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.CheckBudgetResponse.FromString,
                _registered_method=True)
        self.ReportUsage = channel.unary_unary(
                '/agent_platform.ControlPlane/ReportUsage',
                request_serializer=agent__platform__pb2.ReportUsageRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ReportUsageResponse.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/agent_platform.ControlPlane/GetUsage',
                request_serializer=agent__platform__pb2.GetUsageRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.UsageSummaryProto.FromString,
                _registered_method=True)
        self.GetAuditLog = channel.unary_unary(
                '/agent_platform.ControlPlane/GetAuditLog',
                request_serializer=agent__platform__pb2.GetAuditLogRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.GetAuditLogResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer(object):
    """============================================================================
    Services
    ============================================================================

    """

    def CreateOrganization(self, request, context):
        """Organization management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Agent identity management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Policy management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBudget(self, request, context):
        """Budget management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUsage(self, request, context):
        """Usage tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLog(self, request, context):
        """Audit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=agent__platform__pb2.CreateOrgRequest.FromString,
                    response_serializer=agent__platform__pb2.OrganizationProto.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=agent__platform__pb2.GetOrgRequest.FromString,
                    response_serializer=agent__platform__pb2.OrganizationProto.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=agent__platform__pb2.ListOrgsRequest.FromString,
                    response_serializer=agent__platform__pb2.ListOrgsResponse.SerializeToString,
            ),
            'DeleteOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrganization,
                    request_deserializer=agent__platform__pb2.DeleteOrgRequest.FromString,
                    response_serializer=agent__platform__pb2.DeleteOrgResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__platform__pb2.RegisterAgentRequest.FromString,
                    response_serializer=agent__platform__pb2.AgentIdentityProto.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=agent__platform__pb2.GetAgentRequest.FromString,
                    response_serializer=agent__platform__pb2.AgentIdentityProto.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=agent__platform__pb2.ListAgentsRequest.FromString,
                    response_serializer=agent__platform__pb2.ListAgentsResponse.SerializeToString,
            ),
            'DeactivateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateAgent,
                    request_deserializer=agent__platform__pb2.DeactivateAgentRequest.FromString,
                    response_serializer=agent__platform__pb2.DeactivateAgentResponse.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=agent__platform__pb2.SetPolicyRequest.FromString,
                    response_serializer=agent__platform__pb2.PolicyProto.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=agent__platform__pb2.GetPolicyRequest.FromString,
                    response_serializer=agent__platform__pb2.PolicyProto.SerializeToString,
            ),
            'EvaluatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePolicy,
                    request_deserializer=agent__platform__pb2.EvaluatePolicyRequest.FromString,
                    response_serializer=agent__platform__pb2.PolicyDecisionProto.SerializeToString,
            ),
            'SetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBudget,
                    request_deserializer=agent__platform__pb2.SetBudgetRequest.FromString,
                    response_serializer=agent__platform__pb2.BudgetProto.SerializeToString,
            ),
            'GetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBudget,
                    request_deserializer=agent__platform__pb2.GetBudgetRequest.FromString,
                    response_serializer=agent__platform__pb2.BudgetProto.SerializeToString,
            ),
            'CheckBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBudget,
                    request_deserializer=agent__platform__pb2.CheckBudgetRequest.FromString,
                    response_serializer=agent__platform__pb2.CheckBudgetResponse.SerializeToString,
            ),
            'ReportUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUsage,
                    request_deserializer=agent__platform__pb2.ReportUsageRequest.FromString,
                    response_serializer=agent__platform__pb2.ReportUsageResponse.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=agent__platform__pb2.GetUsageRequest.FromString,
                    response_serializer=agent__platform__pb2.UsageSummaryProto.SerializeToString,
            ),
            'GetAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLog,
                    request_deserializer=agent__platform__pb2.GetAuditLogRequest.FromString,
                    response_serializer=agent__platform__pb2.GetAuditLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_platform.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_platform.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane(object):
    """============================================================================
    Services
    ============================================================================

    """

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/CreateOrganization',
            agent__platform__pb2.CreateOrgRequest.SerializeToString,
            agent__platform__pb2.OrganizationProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetOrganization',
            agent__platform__pb2.GetOrgRequest.SerializeToString,
            agent__platform__pb2.OrganizationProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/ListOrganizations',
            agent__platform__pb2.ListOrgsRequest.SerializeToString,
            agent__platform__pb2.ListOrgsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/DeleteOrganization',
            agent__platform__pb2.DeleteOrgRequest.SerializeToString,
            agent__platform__pb2.DeleteOrgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/RegisterAgent',
            agent__platform__pb2.RegisterAgentRequest.SerializeToString,
            agent__platform__pb2.AgentIdentityProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetAgent',
            agent__platform__pb2.GetAgentRequest.SerializeToString,
            agent__platform__pb2.AgentIdentityProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/ListAgents',
            agent__platform__pb2.ListAgentsRequest.SerializeToString,
            agent__platform__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/DeactivateAgent',
            agent__platform__pb2.DeactivateAgentRequest.SerializeToString,
            agent__platform__pb2.DeactivateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/SetPolicy',
            agent__platform__pb2.SetPolicyRequest.SerializeToString,
            agent__platform__pb2.PolicyProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetPolicy',
            agent__platform__pb2.GetPolicyRequest.SerializeToString,
            agent__platform__pb2.PolicyProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/EvaluatePolicy',
            agent__platform__pb2.EvaluatePolicyRequest.SerializeToString,
            agent__platform__pb2.PolicyDecisionProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/SetBudget',
            agent__platform__pb2.SetBudgetRequest.SerializeToString,
            agent__platform__pb2.BudgetProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetBudget',
            agent__platform__pb2.GetBudgetRequest.SerializeToString,
            agent__platform__pb2.BudgetProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/CheckBudget',
            agent__platform__pb2.CheckBudgetRequest.SerializeToString,
            agent__platform__pb2.CheckBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/ReportUsage',
            agent__platform__pb2.ReportUsageRequest.SerializeToString,
            agent__platform__pb2.ReportUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetUsage',
            agent__platform__pb2.GetUsageRequest.SerializeToString,
            agent__platform__pb2.UsageSummaryProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ControlPlane/GetAuditLog',
            agent__platform__pb2.GetAuditLogRequest.SerializeToString,
            agent__platform__pb2.GetAuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExecutionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/agent_platform.ExecutionService/ExecuteTask',
                request_serializer=agent__platform__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=agent__platform__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__platform__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=agent__platform__pb2.ExecuteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_platform.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_platform.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_platform.ExecutionService/ExecuteTask',
            agent__platform__pb2.ExecuteTaskRequest.SerializeToString,
            agent__platform__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
